export const SYSTEM_ROLE = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  SUPPLIER_MANAGER: "SUPPLIER_MANAGER",
  BOOKING_MANAGER: "BOOKING_MANAGER",
  STAFF: "STAFF",
} as const;

export const SYSTEM_ROLE_ARRAY = Object.values(SYSTEM_ROLE);
